spring:
  application:
    name: shades

downstream:
  connectIp: http://192.168.1.30:3000
  api:
    shade:
      listDevices:
        path: /list_devices
      openShade:
        path: /open_shade/{mac}
      closeShade:
        path: /close_shade/{mac}
      setShadePosition:
        path: /set_shade_position/{mac}/{position}
      stopShade:
        path: /stop_shade/{mac}
      getShadeState:
        path: /get_shade_state/{mac}
      getLightLevel:
        path: /get_light_level/{mac}
      getBatteryLevel:
        path: /get_battery_level/{mac}
  devices:
    - mac: "d8:85:46:5b:0c:55"
      name: OfficeLeft
      groups: ["Office", "Seasonal", "All"]
    - mac: "de:75:b8:79:20:4c"
      name: OfficeMiddle
      groups: ["Office", "Seasonal", "All"]
    - mac: "de:b8:32:e4:63:21"
      name: OfficeRight
      groups: ["Office", "Seasonal", "All"]
    - mac: "c6:08:10:c8:f7:64"
      name: KitchenRear
      groups: ["Kitchen", "All"]
    - mac: "d0:e4:4e:28:c5:ae"
      name: KitchenSide
      groups: ["Kitchen", "Seasonal", "All"]
    - mac: "dc:e4:75:97:b0:60"
      name: LivingLeft
      groups: ["Living", "All"]
    - mac: "cd:1e:bd:f5:9b:af"
      name: LivingMiddle
      groups: ["Living", "All"]
    - mac: "fd:a1:05:1a:e8:d6"
      name: LivingRight
      groups: ["Living", "All"]



#  macMap.put("c6:08:10:c8:f7:64", "KitchenRear");
#  macMap.put("d0:e4:4e:28:c5:ae", "KitchenSide");
#  macMap.put("dc:e4:75:97:b0:60", "LivingLeft");
#  macMap.put("cd:1e:bd:f5:9b:af", "LivingMiddle");
#  macMap.put("fd:a1:05:1a:e8:d6", "LivingRight");
#  macMap.put("d8:85:46:5b:0c:55", "OfficeLeft");
#  macMap.put("de:75:b8:79:20:4c", "OfficeMiddle");
#  macMap.put("de:b8:32:e4:63:21", "OfficeRight");
