spring:
  application:
    name: shades

downstream:
  connectIp: http://192.168.1.30:3000
  api:
    shade:
      listDevices:
        path: /list_devices
      openShade:
        path: /open_shade/{mac}
      closeShade:
        path: /close_shade/{mac}
      setShadePosition:
        path: /set_shade_position/{mac}/{position}
      stopShade:
        path: /stop_shade/{mac}
      getShadeState:
        path: /get_shade_state/{mac}
      getLightLevel:
        path: /get_light_level/{mac}
      getBatteryLevel:
        path: /get_battery_level/{mac}

